language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  api_key:
    secure: bTYGzvdejFyS+OkwprX6b5LW7yo7IlfUsOXpS8/qW2EWCv23JgMgh4Wz3MCkjSlhZ0m0PWVMZz/Exz3S+EwP92mYEmGrnFbCsjRWpIa96JbxxoL/chXZVjLtvnpPtWwP1L5lU36KMFv3kTGg26o9nSNOV8Nt6nA7oVeAzTkcmofjqMZzPruBaGgc+8h/ib7VNs7bd5QusmSCvNbsT8NjAugPQ6Dv75l3n9bhK7DaL+XG9If1LhlotZ0Vy2IX688vWvtkzLCzsW51xC4i9vMQLQw8rhCQ3SW/fWHM76vNvkvi4w1QPzsfUd9EAB4DtJOHIX8YfyevVnImvmSJr5bJLuQQXeCGYPoQZQqOtqikEG7RO8mKzBMXEvSxeJQUqrnfEz0Ui6m98wtFmZ8bxVZJmL8YfPtsVz2yu9S1qVfEWO0QZ+iExShJ5/awUtklLsCaC0dnYsvFoqt+YCcL+vNYfYablEqpR5xcZwVqjYDkg5KF9AM9+xbVc5MtzUnCk0Fg8HdochgbdHqgcNWAD3JIbNAeNH0hLQ1g0gc1w1i2LBOFNRxCbx24pvtMzm9paYTsSXd2+5CiO9pB+GZGJ6TEguxcNLkyWZ8IuYRS4zBrRs6ZhIW+cfmXAJzVY1m0iFYFJ4lDrYLyEuaoEM+TCGn+ja+nSCrVHdKno8oPfQdOqvI=
