language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  api_key:
    secure: oDC7bOmRd0IMxnaxumunCAQN67tTWImOA4Sxucj+2JG1gyCjtr62ZKI5mLlQKZu7YIpoDpLIxpRxIfo7Ga/fIiEydclxndMWE7vTCCqyfwTrnzOUTincFsjXNVy/wk7hor1f3J6dR50c/vjKW3OrBCQL4aGEGpZrkVg4UtNdcSE59RihNy6SnL6IbLMZJfqgS0VzSi22kczIeWbHpstiXikxpx9R5Dc/qBMhX9FxuBCCT7uoR2riGNMk1uB/RSHhLsbDiB8cFYSGK5TYvs7u3KtE/66gexp9RHIs5YpI2yxDeTjzDugfh4j8yRF/gRP96dSdbugcGILgvaAIMYmpYF3+5LfCvnQm0ZyRrlS6UC2JOf0s4itwbalE+s5JNMEoiC7fJ3Mt9pKf2rdlwUpdJN3A2uRAbLVWZ+zOs9lgcSl7wIn50dU4PvL9yUnRl01bqS6ae0FcliGSxk7gIlJo/TX0Team9HYB2nG2nH92jFU7ifvElBZSi0ItMf+xPS3QM7j91Mnz4RbMUzoaXCMdGfsUAK0vkkiFep0qFu6xbeaIVH83ep4XaIu5i63C0UhLrkghLJL+x6yH3ZLVn9xVo6aYRgqWI2N3g4x60rpIhkE7zA/YWJIagt7X8ATSgf9zSs7Vw7n6VllotKAc3uN+RqPXnbD9tfKMarsG7OYACTg=
