language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  api_key:
    secure: kscdqpi8IUCGuKE64tWBAX2lOpvwSLkq3m0m81NU5JR7qUs580Az8sh/Ke/jYzleTe2rho8Nlk/uKAFYhjJ6S81iEZknY8rqO0TUyS0MvMfM7VHq7xFb8MRcLqISzzBlRPjN7Arf6F2AZuvNp029nmYGnNY1utbwDWo5eMbDunTWRZbsYaa9VHBf8u8Ap6+DBV9dhFJ+KoFtziW0qqxJSQJZA3N1c/7cChMpfGYQj4hmbyoeGP/9nxV9V7JLUliJ/KqPFqNSH3yGAqEoIFJM3M7LHhGDAouXSWnd3BFimwQohlMH9Lrei7rE3q9GY0rOZoUXPC4n/UTGUutETtapv4Z334BWcL9ADqholNT3NUqaCkdHI8kXr4oo5hSyHnJlRid53m4L3iBwMYkoENHefGzK1EICrC0qSzaOrcmPpaSy1rEwIk4qIQfPoewOa5oLy1uuJcXLU2ypmcP+betbiNwoHj+r69I1vfHtV2S/mX/sL16Tko6fj8Qal+lJeXRKOykIVNqunm7wlQmwgpkdEbpFz2P4E5DU+mFSrHiwMQ6DEkSEXvagXcJDn0kyPtm1YYCBB5mQZaL7fn1OqBYsSYffg+SXMJsO8cGcnTdQ/tFy7N/Js+CIVkAAtXjJ11a+7tsTTUHeEK5JAGRthPhmdMNfd4gxekfdMFJcuDRNGqs=
