language: python
dist: xenial
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  api_key:
    secure: i/F21Y2TF+VPJerMlr+KXTCTSj6HdHOy3G0OMUEk8+7Zl8ihoBg/KTngUkvy78sibWJCxmEEgawQQ6REVcU0u8fxrtTt+juquX0TmIney/A6aSanlg1d9hrhb/TVs0kUfTKgz+ULOyvXQRlUMlyqhpyOo94HDMQjSZCqa8aJ5CMAjdBiO8RpIRKA8TUlAqxwof5lJEKNnfF1PE5rO47rsR64TrRoBC1dUbhOcUGGd1HyBJi6fNDxbuXBsSXELDU0kLFUBU5hrbhWGkSL+Y8sa9tE9TyabmYBbHtBOyfAya1PfhIUmssEtNvALmn2z2M2YBQ314b0k0xjIAYDVmOR83w00GkWqAgGAxz84Q4hLwnNDojcpZ/M455QlF5VtkYNCnLQGhPs/KnqhYAqrDS2nStUbieg/sGdHq/MS6DwVpc+AHg8yYUmTfAqNiCzk3wCdYCIOyxYn7NMpp6s4Lu0ONsi/LzXBFI7UVACry5/29yfybseFuHv5TEbrpjWrNttH/9dTpQ0wGz2y08FzWw13SqdMNFdImFo3Gzt+mi/b0jJmWlCDaVe8uMlQOnH8PmFnylDmlc38UXcVsC+/N58XAUoficeAOhkhIfMiZ80Q9ud/fJAh3QCgceOj/gYFBjuyNlgFPiIAjQPIm5syrVNfPic5dwcZusTugIlO926al8=
